HOST: 'localhost'
FACEBOOK_APP_ID: '1063327573744287'
FACEBOOK_APP_SECRET: 'cc3150d44cbba609a8d5b33b29a0e363'
TWITTER_APP_ID: 'QwijnjyzAzkb0O2QCFrKvs1CZ'
TWITTER_APP_SECRET: 'QYchRapbS2cohrfGbYK4mUs4V8If3XsLLpWqvtl9sUb0RkNJLT'
LINKED_IN_APP_ID: '81nasthj15nmm0'
LINKED_IN_APP_SECRET: '1VCCDZA5a5DGeUzO'
GOOGLE_OAUTH2_APP_ID: '326842851913-d5pjtfjlm09sbrqi6tqtmasrujkidak6.apps.googleusercontent.com'
GOOGLE_OAUTH2_APP_SECRET: 'SLVZTHIKAHYUgs49_c-Kpf6q'
