default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: root
  password: password

development:
  <<: *default
  database: food-review-dev

test:
  <<: *default
  database: food-review-test
